services:
  nginx-service:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
  static-site:
    image: nginx:latest
    container_name: static-site
    ports:
      - "5555:80"
    volumes:
      - ./static-site:/usr/share/nginx/html
